### ISSUE TITLE
Ability to use any DNS server.

### ISSUE THREAD

**Issue by true2thepen** [vsevex/dnsolve#2]
Feature Request:

Ability to use any dns server. This would give the ability to use not only public dns servers; but, internal private dns servers as well.

**Comment by vsevex** [comment]
Hi, thank you for your contribution.

This is a simple wrapper to do DoH (DNS over HTTPS) lookups, so private DNS lookups can not be done in this solution. For further information please take a look at the markup file. I guess there is not any solution to do this in Dart (package or library) at the moment, but it can be ideal for you to search for the correct answer in the community. In the future, private DNS lookups can be implemented, but I don't need to add this functionality to the package for now.
